DT RF LR SVM

In [208]:
import pandas as pd

In [209]:
data = pd.read_csv("dataset/car.data", header=None)
df = pd.DataFrame(data)

In [210]:
df

          0      1      2     3      4     5      6
0     vhigh  vhigh      2     2  small   low  unacc
1     vhigh  vhigh      2     2  small   med  unacc
2     vhigh  vhigh      2     2  small  high  unacc
3     vhigh  vhigh      2     2    med   low  unacc
4     vhigh  vhigh      2     2    med   med  unacc
...     ...    ...    ...   ...    ...   ...    ...
1723    low    low  5more  more    med   med   good
1724    low    low  5more  more    med  high  vgood
1725    low    low  5more  more    big   low  unacc
1726    low    low  5more  more    big   med   good
1727    low    low  5more  more    big  high  vgood

[1728 rows x 7 columns]

In [211]:
df.columns =['buying', 
            'maint',
            'doors',
            'persons',
            'lug_boot',
            'safety',
            'Class']

In [212]:
df

     buying  maint  doors persons lug_boot safety  Class
0     vhigh  vhigh      2       2    small    low  unacc
1     vhigh  vhigh      2       2    small    med  unacc
2     vhigh  vhigh      2       2    small   high  unacc
3     vhigh  vhigh      2       2      med    low  unacc
4     vhigh  vhigh      2       2      med    med  unacc
...     ...    ...    ...     ...      ...    ...    ...
1723    low    low  5more    more      med    med   good
1724    low    low  5more    more      med   high  vgood
1725    low    low  5more    more      big    low  unacc
1726    low    low  5more    more      big    med   good
1727    low    low  5more    more      big   high  vgood

[1728 rows x 7 columns]

In [213]:
#인코딩
df = pd.get_dummies(df, columns =['buying', 'maint', 'doors', 'persons','lug_boot', 'safety'])

In [214]:
df

,Class,buying_high,buying_low,buying_med,buying_vhigh,maint_high,maint_low,maint_med,maint_vhigh,doors_2,...,doors_5more,persons_2,persons_4,persons_more,lug_boot_big,lug_boot_med,lug_boot_small,safety_high,safety_low,safety_med
0,unacc,False,False,False,True,False,False,False,True,True,...,False,True,False,False,False,False,True,False,True,False
1,unacc,False,False,False,True,False,False,False,True,True,...,False,True,False,False,False,False,True,False,False,True
2,unacc,False,False,False,True,False,False,False,True,True,...,False,True,False,False,False,False,True,True,False,False
3,unacc,False,False,False,True,False,False,False,True,True,...,False,True,False,False,False,True,False,False,True,False
4,unacc,False,False,False,True,False,False,False,True,True,...,False,True,False,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1723,good,False,True,False,False,False,True,False,False,False,...,True,False,False,True,False,True,False,False,False,True
1724,vgood,False,True,False,False,False,True,False,False,False,...,True,False,False,True,False,True,False,True,False,False
1725,unacc,False,True,False,False,False,True,False,False,False,...,True,False,False,True,True,False,False,False,True,False
1726,good,False,True,False,False,False,True,False,False,False,...,True,False,False,True,True,False,False,False,False,True
1727,vgood,False,True,False,False,False,True,False,False,False,...,True,False,False,True,True,False,False,True,False,False

In [215]:
#라벨링

from sklearn.preprocessing import LabelEncoder

label=LabelEncoder()

df['buying_high']=label.fit_transform(df['buying_high'])
df['buying_low']=label.fit_transform(df['buying_low'])
df['buying_med']=label.fit_transform(df['buying_med'])
df['buying_vhigh']=label.fit_transform(df['buying_vhigh'])
df['maint_high']=label.fit_transform(df['maint_high'])
df['maint_low']=label.fit_transform(df['maint_low'])
df['maint_med']=label.fit_transform(df['maint_med'])
df['maint_vhigh']=label.fit_transform(df['maint_vhigh'])
df['doors_2']=label.fit_transform(df['doors_2'])
df['doors_3']=label.fit_transform(df['doors_3'])
df['doors_4']=label.fit_transform(df['doors_4'])
df['doors_5more']=label.fit_transform(df['doors_5more'])
df['persons_2']=label.fit_transform(df['persons_2'])
df['persons_4']=label.fit_transform(df['persons_4'])
df['persons_more']=label.fit_transform(df['persons_more'])
df['lug_boot_big']=label.fit_transform(df['lug_boot_big'])
df['lug_boot_med']=label.fit_transform(df['lug_boot_med'])
df['lug_boot_small']=label.fit_transform(df['lug_boot_small'])
df['safety_high']=label.fit_transform(df['safety_high'])
df['safety_low']=label.fit_transform(df['safety_low'])
df['safety_med']=label.fit_transform(df['safety_med'])

df

,Class,buying_high,buying_low,buying_med,buying_vhigh,maint_high,maint_low,maint_med,maint_vhigh,doors_2,...,doors_5more,persons_2,persons_4,persons_more,lug_boot_big,lug_boot_med,lug_boot_small,safety_high,safety_low,safety_med
0,unacc,0,0,0,1,0,0,0,1,1,...,0,1,0,0,0,0,1,0,1,0
1,unacc,0,0,0,1,0,0,0,1,1,...,0,1,0,0,0,0,1,0,0,1
2,unacc,0,0,0,1,0,0,0,1,1,...,0,1,0,0,0,0,1,1,0,0
3,unacc,0,0,0,1,0,0,0,1,1,...,0,1,0,0,0,1,0,0,1,0
4,unacc,0,0,0,1,0,0,0,1,1,...,0,1,0,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1723,good,0,1,0,0,0,1,0,0,0,...,1,0,0,1,0,1,0,0,0,1
1724,vgood,0,1,0,0,0,1,0,0,0,...,1,0,0,1,0,1,0,1,0,0
1725,unacc,0,1,0,0,0,1,0,0,0,...,1,0,0,1,1,0,0,0,1,0
1726,good,0,1,0,0,0,1,0,0,0,...,1,0,0,1,1,0,0,0,0,1
1727,vgood,0,1,0,0,0,1,0,0,0,...,1,0,0,1,1,0,0,1,0,0

In [216]:
df.isna().sum()

Class             0
buying_high       0
buying_low        0
buying_med        0
buying_vhigh      0
maint_high        0
maint_low         0
maint_med         0
maint_vhigh       0
doors_2           0
doors_3           0
doors_4           0
doors_5more       0
persons_2         0
persons_4         0
persons_more      0
lug_boot_big      0
lug_boot_med      0
lug_boot_small    0
safety_high       0
safety_low        0
safety_med        0
dtype: int64

In [217]:
from sklearn.model_selection import train_test_split
x = df.drop(['Class'], axis=1)
y = df['Class']

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42)

In [218]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((1296, 21), (432, 21), (1296,), (432,))

In [219]:
# DT

from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.tree import DecisionTreeClassifier

clf_dt = DecisionTreeClassifier(random_state=0)
clf_dt.fit(x_train, y_train)

pred_dt = clf_dt.predict(x_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))

--- Decision Tree Classifier ---
0.9722222222222222
[[ 96   4   0   3]
 [  0  14   0   1]
 [  1   0 293   0]
 [  1   2   0  17]]

In [220]:
# SVM

from sklearn.svm import SVC

clf_svm = SVC(random_state=0)
clf_svm.fit(x_train, y_train)

pred_svm = clf_svm.predict(x_test)

print("\n--- SVM Classifier ---")
print(accuracy_score(y_test, pred_svm))
print(confusion_matrix(y_test, pred_svm))

--- SVM Classifier ---
0.9722222222222222
[[ 93   7   0   3]
 [  0  14   0   1]
 [  0   0 294   0]
 [  1   0   0  19]]

In [221]:
# LR

from sklearn.linear_model import LogisticRegression

clf_lr = LogisticRegression(random_state=0)
clf_lr.fit(x_train, y_train)

pred_lr = clf_lr.predict(x_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))

--- Logistic Regression Classifier ---
0.9166666666666666
[[ 87   6  10   0]
 [  8   5   0   2]
 [  8   0 286   0]
 [  2   0   0  18]]

In [222]:
# RF

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import pandas as pd

print ("\n--- Random Forest ---")
rf_clf = RandomForestClassifier(random_state=0)
rf_clf.fit(x_train, y_train)
pred = rf_clf.predict(x_test)
print(accuracy_score(y_test,pred))
print (confusion_matrix(y_test, pred))

--- Random Forest ---
0.9583333333333334
[[ 92   6   3   2]
 [  3  11   0   1]
 [  2   0 292   0]
 [  1   0   0  19]]